/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../views/error/403.vue')['default']
    404: typeof import('./../views/error/404.vue')['default']
    Avatar: typeof import('./../components/Avatar.vue')['default']
    BaseMessage: typeof import('./../components/Message/types/BaseMessage.vue')['default']
    Chat: typeof import('./../views/chat/index.vue')['default']
    ChatBottom: typeof import('./../views/chat/chatBottom/index.vue')['default']
    ChatMiddle: typeof import('./../views/chat/chatMiddle/index.vue')['default']
    ChatTop: typeof import('./../views/chat/chatTop/index.vue')['default']
    CollapseTransition: typeof import('./../components/Transitions/CollapseTransition.vue')['default']
    DarkMode: typeof import('./../components/DarkMode.vue')['default']
    Description: typeof import('./../views/chat/chatTop/components/Description.vue')['default']
    DoubleChecks: typeof import('./../views/chat/chatMiddle/components/DoubleChecks.vue')['default']
    ExpandTransition: typeof import('./../components/Transitions/ExpandTransition.vue')['default']
    FadeTransition: typeof import('./../components/Transitions/FadeTransition.vue')['default']
    Home: typeof import('./../views/home/index.vue')['default']
    IconButton: typeof import('./../components/IconButton.vue')['default']
    ImageMessage: typeof import('./../components/Message/types/ImageMessage.vue')['default']
    ImageViewer: typeof import('./../components/ImageViewer/index.vue')['default']
    InformationDivider: typeof import('./../components/InformationDivider.vue')['default']
    InputText: typeof import('./../components/Inputs/InputText.vue')['default']
    Message: typeof import('./../components/Message/index.vue')['default']
    PaymentMessage: typeof import('./../components/Message/types/PaymentMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleTransition: typeof import('./../components/Transitions/ScaleTransition.vue')['default']
    SlideTransition: typeof import('./../components/Transitions/SlideTransition.vue')['default']
    TextMessage: typeof import('./../components/Message/types/TextMessage.vue')['default']
    Toast: typeof import('./../components/Toast.vue')['default']
    ToolBar: typeof import('./../components/ImageViewer/components/ToolBar.vue')['default']
    Validate: typeof import('./../views/validate/index.vue')['default']
    VHeader: typeof import('./../views/validate/components/VHeader.vue')['default']
    VideoMessage: typeof import('./../components/Message/types/VideoMessage.vue')['default']
    VideoPlayer: typeof import('./../components/VideoPlayer.vue')['default']
    Watchout: typeof import('./../views/validate/components/Watchout.vue')['default']
  }
}
